### ISSUE TITLE
Implement coordinating mechanism for package versions

### ISSUE THREAD

**Issue by jcconway** [gentzkow/template#30]
The goal of this issue is to incorporate into the current template a way to standardize the _versions_ of packages used in a given project. Currently, necessary packages can be downloaded via the programs in [setup/](https://github.com/gentzkow/template/tree/5dc24e9f299b22c818c6b9a20eea178e0c27f0c3/setup). It may still be the case that individuals end up with different packages on their local computers, which can lead to errors or differences in output. As of now, there is no mechanism by which we ensure that all necessary programs have in fact been downloaded, nor do we ensure that the users have the expected version of a package. We seek to resolve that potential pitfall in this issue.

**Comment by jcconway** [comment]
Our more specific thoughts for potential ways to implement this by program are as follows:
- _Stata_: Store packages in a lib/ado/ folder, and have Stata code files change their adopath to this folder.
- _Python_ and _R_: Create a specific Anaconda environment for the repo, created via programs in the repo with all necessary packages and versions.

We're still investigating potential solutions.

**Comment by zkashner** [comment]
@jcconway I have been re-visiting this issue and agree with your first two thoughts. Some details I would add are:

1. For Stata to be entirely the same, I believe we must ensure that users have the same version of Stata installed (i.e. 15 vs 16). This seems to be a good plan that (hopefully) will not be too memory intensive since there are very few dependencies to Stata ado files.
2. We can use miniconda to avoid downloading all of the associated files with a full anaconda download. This can be easily downloaded from homebrew. It has the benefit of ensuring that package dependencies are satisfied comprehensively.
3. We can specify the environment requirements in a `yaml` file similar to the current requirements.txt that contains the required packages for both python and R (as well as the versions of each of these programs). This is diffable and can be updated collaboratively in the Git repo.
4. I need to find a way to activate conda to make it possible to use virtual environments without  making base conda the default python installation so that co-authors and collaborators do not see changes to their normal python and R usage.

Please let me know if you have any thoughts, otherwise I will go forward with this.

**Comment by jcconway** [comment]
Thanks @zkashner! Here are my replies to the [above](https://github.com/gentzkow/template/issues/30#issuecomment-693661150):

> 1. For Stata to be entirely the same, I believe we must ensure that users have the same version of Stata installed (i.e. 15 vs 16). This seems to be a good plan that (hopefully) will not be too memory intensive since there are very few dependencies to Stata ado files.

I believe this can be accomplished using the `version` command within Stata, rather than requiring that users have the same version installed. With this command, users with say Stata 15 and Stata 16 should get the same output so long as all .do files specify `version #`, where `#` is a number <=15. If some of these .do files use commands introduced in Stata 16, then obviously all users would need Stata 16 or higher. I think the main difficulty in this issue is coordinating on the version of installed packages, rather than on the version of Stata itself.

On (2) and (4), that sounds good to me. 

On (3), is your idea that this yaml file could then be used automatically as part of `setup/`, so that users can easily set up the package versions in the project conda environment accordingly? If so, that sounds great!

**Comment by zkashner** [comment]
@jcconway thanks for your quick response!
Also, this:

> I believe this can be accomplished using the version command within Stata, rather than requiring that users have the same version installed

is great news and I definitely defer to you on all matters regarding Stata. Just to be absolutely clear, all versions of Stata 15 are equivalent and there are not intermediate updates, correct?

On (3) it would be a nearly identical process to the current setup process just replacing pip installs and CRAN calls with a conda yaml file. I believe that it would be quite easy to use and to install. The only downside is remembering to initialize the virtual environment when debugging and doing individual file runs. Luckily, we could automatically initialize it in `make.py`.
It would have the same drawbacks as the current system where people do not always update if the requirements change during development. Although, I could look into creating some sort of ad-hoc auto-update system.

**Comment by jcconway** [comment]
Thanks @zkashner!

> Just to be absolutely clear, all versions of Stata 15 are equivalent and there are not intermediate updates, correct?

^This is correct to the best of my knowledge.

On 3), your plan sounds good to me. I think ideally we'd display a warning if package versions differ from the requirements in the yaml file, but I'm happy to defer to you on whatever you think is best and feasible to implement.

**Comment by zkashner** [comment]
@jcconway sounds good! So far (fingers crossed) this has been simple to implement a bare boned version of this so I am optimistic that this is a feasible solution.

**Comment by zkashner** [comment]
@Houdanait when you get a chance could you please check out my branch of the template `issue30_package_versions` and try to follow the steps in the README. Once you get that set up if you can test out on your local machine whether or not the submodules work for all 3 languages (I tested on mine, but good to verify before move to more general use.)

One _big_ goal of this is to determine if the instructions that I have written are straightforward and easy enough to follow. Please flag things that confuse you, or even anything that you have to Google--I want to make this as simple to use and understand as possible!

**Comment by Houdanait** [comment]
Hello, just finished, it all works, a bit lengthy though.
Only one possible commment maybe: 

Since the paragraph usage is to be implemented after setup it would make more sense to have it come after it ? @zkashner

**Comment by zkashner** [comment]
@Houdanait, thanks so much for going through it! When you say lengthy do you mean that it takes a while to implement, or that it is too verbose?

Will make that change! Great idea.

**Comment by Houdanait** [comment]
@zkashner I meant running time* text is clear and concise

**Comment by zkashner** [comment]
@Houdanait ok awesome, thanks! I think that may be a given if we want to go the virtual env route since we need to download miniconda and JDK. Although, after the first time it will be much faster, hopefully.

**Comment by gentzkow** [comment]
@zkashner At whatever point you all have converged on a solution can you ping me and give me a chance to look at it and weigh in?

**Comment by Houdanait** [comment]
@zkashner @jcconway, I might have missed the initial discussion for this, but  how did you guys choose which packages were needed? Did you just include any package that was used at least once in a project and deemed to be useful potentially for another project to have a set which includes the maximum number of possibly desired packages or ..? 
Because for instance, the R-Crayon package seems very heavy so i was wondering how often we use it?

**Comment by zkashner** [comment]
@Houdanait good question! Currently the environment has the minimum number of packages (I believe) that are required to successfully run the test example that Zong implemented in #23 for all 3 languages (R, Python, and Stata). It is currently somewhat heavy because it relies upon the tidyverse in R (which I believe has crayon as a dependency). The idea is that on any project if any of these packages were unnecessary they could very easily be removed.

**Comment by gentzkow** [comment]
Thought here: I think we want to make sure the only dependencies for the template are very common + widely used packages. My impression is `tidyverse` satisfies that criterion. But if we're using anything that doesn't, we should confirm that we really need it.

**Comment by zkashner** [comment]
@gentzkow, @Houdanait I believe that the only packages (and their dependencies) that we attach that are not needed for the base functionality of the repo are:

#### Python
- linearmodels (linear modelling)
- matplotlib (plotting)
- numpy (matrix and vector operations in python)

#### R
- tidyverse (common dialect of R that seems widely used enough to be needed)
- plm (panel linear models)
- janitor (used commonly to clean data)

In my opinion, all of these are commonly used enough to justify all users importing them as a default.

**Comment by Houdanait** [comment]
@zkashner we have this : 
"One way to get around this is to include `sudo` (or the Windows equivalent of running in administrative mode) in your bash command.
```
sudo python -m pip install -r requirements.txt
```

However, we caution against this (in particular for Macs) given the potential security risks. Instead, we recommend including the `--user` flag to your bash command.
```
python -m pip install --user -r requirements.txt
```
" 

My question is, why do we give the two options? it might seem confusing to stay you can do actionA but we actually recommend you do not do actionB and instead do action B..
My comment might be extraneous, but maybe we can just keep the `python -m pip install --user -r requirements.txt
` command which is the one we came up with in the set up when we had the issues?

**Comment by zkashner** [comment]
@Houdanait I updated the README and removed much of the `pip` information which is made redundant by `conda`. Thanks for the feedback!

**Comment by zkashner** [comment]
Thank you @Houdanait for your recommendations! @gentzkow I believe that we have converged upon a solution that is ready for feedback. If you want to try it out yourself the updated instructions and implementation can be found in this branch (`issue30_package_versions`). I've also written out a description of the changes, involved trade-offs, and potential improvements that I will hold off on implementing until I get more feedback on this! 

## Overview
### Solution for R and Python
We manage R and Python packages (and the base installation and version of these programs) using `miniconda` which can create a virtual environment for any given project--thus isolating all versions of packages and the version of R/Python used to a specific project. 
### Solution for Stata
We create a simple ado file to be used at the beginning of each Stata script that standardizes the version used, updates the `adopath` to only search the base install and a folder of ado files stored in `lib/ado`

## Python and R
### Pros

- Can easily manage multiple projects with different dependencies at once without affecting base installs of R and Python
- The creation of the environment can be executed from a `yaml` file clearly delineating the needed version which is diffable and can be changed by collaborators on Git. 

### Cons
- Setup takes a non-trivial amount of time. This will get quicker after the initial install of `miniconda` and `oracle-jdk` but because all of the packages are being freshly installed this is not very fast. Luckily, because the packages tend to not be very large (especially compared to data files) this is not very memory heavy. 

## Stata
### Pros

- Ensures that all Stata users have the same packages (and versions) downloaded.

### Cons

- Need to add two lines to the beginning of each Stata file to ensure that Stata environment is updated correctly.
- Potential re-download of some Stata files. Luckily, these are not very memory intensive, especially since they contain very few dependencies.

## Potential extensions 
There are a few more ideas that I have that I will hold off on implementing until I get some feedback about the current draft that could further improve this.

- Script that either auto installs new packages via conda or alerts to changes that are required by updates to the `conda_env.yaml` file. This would be an improvement to the status quo where most users do not revisit the `setup/` module during development until something fails to run correctly due to missing dependencies 
- If we do not add `lib/ado` to the Git ignore then the Stata install can be tracked by Git and absolutely ensures that there is no difference or error between users.
- I could alter the Stata builder to auto-include the code to update the environment as required, so that users do not need to remember to include these lines.

**Comment by jcconway** [comment]
@zkashner, I haven't yet looked through this implementation in detail but wanted to share one quick thought on the Stata portion. I don't think the `version` set in [standardize_env.ado](https://github.com/gentzkow/template/blob/bfdeea6c0f7404d227213dbedd3bdec0308392e3/lib/stata/standardize_env.ado) will persist beyond the program itself. Here's the log file from a test I ran to confirm this issue: [log.txt](https://github.com/gentzkow/template/files/5248684/log.txt)

**Comment by zkashner** [comment]
@jcconway good catch! A possible solution is to specify this in each stata `do` file right before `standardize_env` but I can also look into other cleaner solutions.

**Comment by jcconway** [comment]
> @jcconway good catch! A possible solution is to specify this in each stata `do` file right before `standardize_env` but I can also look into other cleaner solutions.

Thanks @zkashner! Another option for implementation would be to use the `include` command to run something like `standardize_env`. The difference between `do filenm.do` and `include filenm.do` is that temporary changes (e.g. specifying the version or creating locals) persist with the latter beyond just the environment of `filenm.do`, while they do not in the former.

**Comment by zkashner** [comment]
@jcconway that is a great solution. I just implemented it in the commit above and checked the version in a similar way as you did, and it worked great!

**Comment by zkashner** [comment]
@Houdanait I am hoping to wrap this issue up, and would love your feedback after we used this updated version of the template on the FB project. Did you find it difficult to use? Would adding a feature to alert you to when your conda env is out of date be useful or not worth the trouble to create?

**Comment by Houdanait** [comment]
Hey @zkashner, i remember finding this version with updated and accurate instructions easier to use than other repos thank you so much for creating this. I'm not sure whether adding a version to alert of out of data conda would be really worth it though?

**Comment by zkashner** [comment]
@Houdanait thank you! I am glad that you liked it.

In that case: @gentzkow, I believe that we have converged upon a solution--and actually have tested it on a real project (albeit one with fake data, but nonetheless)! If you have any comments please let me know, but I believe that this should be ready for feedback (and potentially incorporation).

**Comment by gentzkow** [comment]
Great. Thanks @zkashner! This sounds excellent.

Where do we stand on the potential extensions you mention [here](https://github.com/gentzkow/template/issues/30#issuecomment-695106597)?

**Comment by zkashner** [comment]
@gentzkow I have held off on implementing these extensions as I have considered them more. I would love your feedback on what you think about them.
1. I wonder if this sort of "notification" would be annoying to people (and asked Houda about this [here](https://github.com/gentzkow/template/issues/30#issuecomment-776824778)). I am leaning towards thinking it would be more helpful than annoying, so if you agree I can make that!
2. This is a one line change that I can make that will make everything more standardized but may lead to larger repos. I tend to think it is a good idea, but defer to you.
3. I am beginning to think that this may actually cause more trouble than it is worth. In development I (and other RAs) frequently run `stata` executables from the command line. Adding this to the builder would lead to a case where a script that is run as a one-off would have different behavior than within the larger repo. I believe that this is a case where the costs outweigh the benefits.

**Comment by gentzkow** [comment]
Thanks!

(1) If this is just a warning message I get in the terminal window when I run the build script, the annoyance cost seems like it can't be all that big. So I'd be in favor of implementing.

(2) Stata ado files are very small, so I wouldn't worry about the repo size. And the added robustness + reduction in setup steps seems valuable. Let's implement!

(3) Agree that it's better not to do this.

**Comment by zkashner** [comment]
@gentzkow checking back in on this:

I just implemented the conda status warning check that we discussed above and refactored some to replace a deprecated module. This should be ready for your assessment.

**Comment by gentzkow** [comment]
@zkashner Awesome work here. Here are some comments based on doing an install + run of the repo. Some fit under this issue and some may belong in separate issues.

1. Can we write README.md so it works both for users who are installing miniconda and for users who already have full anaconda installed? If I read the beginning "we manage... using miniconda" I might think I have to install miniconda. It would be nice if the instructions all make sense for both types of users.

2. I think we should refactor README.md so there is a "Setup (Mac & Linux)" section and a separate "Setup (Windows)" section. Right now it's annoying to have windows-specific material in the way if you don't need it.

3. Can we make config_user.yaml optional? Seems like we could just say that if that file doesn't exist set "external:" to empty and set "local: executables:" to default values.

4. When I run check_setup.py I still get the message for the imp module being deprecated

5. Are we sure we want to direct people to use homebrew for the miniconda install? That makes this not work for Windows and also require an extra step. Maybe instead we direct people to the installation page [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/)? Then we can note that it also works to do the install via Homebrew. (Or is the issue that the regular miniconda installer doesn't include oracle-jdk?)

6. I thought we were getting rid of the setup_state.do step. Shouldn't all the ado files we need be included in /lib/stata/? Goal should be that the template doesn't make any changes to the user's machine outside of the conda env.

7. Similarly, what are the cases when we would need setup_r.r? What kinds of packages can't be managed via Conda? Can we get rid of this?

8. Now that we have clean package management via Conda, what about getting rid of separate copy of gslab_make we are keeping in /lib/ and instead have this installed properly as a dependency?

**Comment by gentzkow** [comment]
(9) Another thought on config_user.yaml -- could we get rid of the template file in /setup/ and instead put the template as config_user.yaml at the root, but still include it in .gitignore so changes to it don't get committed?

**Comment by gentzkow** [comment]
(10) Can we revisit the question of whether to have ROOT detected automatically in make.py? I'm thinking we could replace

> ROOT = git.Repo('.', search_parent_directories = True).working_tree_dir

with just

> ROOT = '../..'

This has the cost that if we move a module up or down a level in the directory hierarchy we have to change all the make.py scripts. But this seems like it might be a price worth paying to get rid of this failure point and not have the weird feature that the template actually has to be a Git repo in order to run.

**Comment by gentzkow** [comment]
(11) Per general plan to keep readmes as .md let's change README.txt -> README.md in /raw/

**Comment by zkashner** [comment]
@gentzkow thank you so much for your feedback! I will go about making these changes. To begin to answering your questions:

(1) Yes I can definitely make that change. The current design works for both miniconda and conda, so it will be an easy change!
(2) That sounds like a great way to streamline it. I will do that.
(3) I think we should be able to do that. I will get to working on that, it seems like a nice way to simplify it.
(4) Good catch! I forgot to change that.
(5) As far as I know, it would be completely fine to download miniconda from the page directly. I recommended using homebrew for consistency with a number of other gslab procedures. If you do not object I'll have branched instructions for if you do not have homebrew or you already have homebrew downloaded--since if you already have homebrew set up it is a much simpler download process.
(6) I think that is wise. I kept it since it is a somewhat convenient way to keep track of how to download new stata packages so that they are saved to `lib/stata/` but I agree that this could be done more simply by simply adding those instructions to the README and removing this step.
(7) Great question. I think that unlike with Stata, I would lean towards keeping this. The reason is that there are a number of high quality R packages that are only available on GitHub rather than CRAN (and thus conda). These GitHub packages cannot be managed via conda, so I would lean towards keeping this here but adding instructions to download from specific Git commits rather than simply from the most recent version to keep with the goal of this issue.
(8) I will look into if there is a way to have conda manage gslab_make (either via Github download or if it is simple to add it to a conda channel), but my intuition is that this will not be very easy to do.
(9) Good question. I will look into doing this!
(10) I like this change. This will also be beneficial in creating replication packages, since it is somewhat odd to initialize them as a git repository with no history.
(11) Will do, sorry for missing that.

Thanks so much for your helpful feedback!

**Comment by gentzkow** [comment]
All sounds good. Thanks!

**Comment by zkashner** [comment]
@gentzkow to check in on this: I have updated the repo per nearly all of the discussion we had previously.

A few comments. The way that I resolved your comments 3 & 9 is by highlighting the current behavior. There is no way to have `config_user.yaml` exist and not be tracked. However, we can not track `config_user.yaml` but guarantee that it is there by copying it over from `setup/` during repo setup, which I think is essentially the behavior we were hoping for.

On (8) I believe that it is possible to add gslab_make to `conda`. However, I think that it would be difficult (and make it somewhat tricky to maintain and update). As it stands, we currently have precedent for having packages in `lib/` (as we do with Stata) so I am not too averse to keeping this copy here, particularly since it allows for more customization. Do you have a strong preference on this?

**Comment by gentzkow** [comment]
Thanks @zkashner 

On (3), (9): I am fine dropping (9) and not trying to have config_user.yaml exist in the repo but not be tracked subsequently. I'm also fine having `config_user.yaml` created by setup.

On (8): OK. The main thing I'd worry about is how to make sure updates to gslab_make get pushed to existing repositories. I'm fine keeping gslab_make local in /lib/ and doing updates to it manually, but we should at least make sure the steps for that are easy + well documented. 

Am I right that (2) still hasn't been implemented? It looks to me like the Windows setup is still mixed in w/ the Mac/Linux setup in README.md. Apologies if I'm looking at the wrong version.

**Comment by gentzkow** [comment]
Hmm... additional thought on (3) -- What script would create config_user.yaml? I think the reason we moved away from that before was that we wanted check_setup.py to really be just checking (not doing any setup) and we didn't want to add an additional setup.py script layer. Maybe best just to go with my original suggestion of keeping this part of manual setup but also making the scripts use defaults (and issue a warning) rather than breaking when config_user.yaml is missing?

**Comment by gentzkow** [comment]
Also, it doesn't look to me like (6) was implemented... I still have setup_stata.do... ?

Is it possible there are some changes that weren't pushed? Or that there's some other reason I'm not looking at the right version of the template?

**Comment by zkashner** [comment]
@gentzkow thank you for your feedback! Sorry for all confusion.

On (3)/(9) I didn't realize that we had moved away from that before. It is the current behavior of the repo (before any of my changes) that `check_setup.py` copies the (essentially blank) `config_user.yaml` to the root of the repo and then continues to check. I think that from a style perspective it makes sense to (even if they don't specify `config_user.yaml` to have one so that we do not have a mess of if statements with defaults). As far as I can tell this is the only aspect of setup that `check_setup.py` does.

On (2) I am so sorry--I meant to make a note of this. I split the two instructions and found that after I made the other changes there were very few differences between Windows and Mac/Linux, so I undid the refactor and figured it was best to leave these notes in the main doc. However, in the most recent commit I took these out and added a section at the end about how to tweak the main instructions to make it work for windows.

(6) I wanted to keep `setup_stata.do` to make sure that it was very simple for users to add additional packages to the repo (and make sure that they downloaded them to the correct location). I tried to explain it [here](https://github.com/gentzkow/template/tree/issue30_package_versions#stata), but I apologize if that was unclear. Additionally, given your response of confusion I can very easily rename this script to something like `download_ado.do` or something like that!

**Comment by gentzkow** [comment]
No problem.

Maybe we could do this: Instead of having check_setup.py automatically create config_user.yaml, what if it pauses with a msg saying "It looks like you have not created the configuration file config_user.yaml. Would you like me to create a template version for you now? (Y/N)" 

That seems more consistent w/ the behavior of a "check" script rather than an "install" or "setup" script.

On Stata, just to be sure I understand: The intended behavior is that all Stata scripts are already versioned in /lib/, so the repo setup does not require downloading them. The setup_stata.do script is there only if the user decides to add additional scripts later. Is that right? If so, I like the idea of renaming to `download_stata_ado.do`.

**Comment by zkashner** [comment]
@gentzkow thank you for the feedback
I can implement that for the `check_setup.py`. The only thing is that as it stands the run procedure would break if they chose N. It would be possible but slightly messy to make this robust to that. I create `.conda_info` in running `make.py` to be able to track whether the conda env is up to date, so there are other instances of writing files that are somewhat peripheral to the rest of the script. I am happy to defer to you on this, however!

Done! In the commit above.

**Comment by gentzkow** [comment]
OK. Fine to stick to the status quo if you think it's best.

>

**Comment by zkashner** [comment]
@gentzkow ok, thank you! In that case I believe all your suggested changes have been implemented.
