### ISSUE TITLE
tablefill whitespace

### ISSUE THREAD

**Issue by lboxell** [gentzkow/template#34]
@zkashner,

In one of Matt's projects, I ended up having to change https://github.com/gentzkow/template/blob/3369531210cf54820225c0bbe7c05d0aec631e80/lib/gslab_make/tablefill.py#L51

to 
```
    data = [null if value.strip() in null_strings else value for value in data]
```

because my entries were getting saved as "      . " for some reason with extra whitespace. Stripping whitespace seems benign for this check of null values in tables (e.g., " NA   " or "  .  " or "    ") .

Flagging in case you agree and think its worthwhile to implement.

**Comment by zkashner** [comment]
@lboxell thank you for flagging this. I agree that this would be a positive improvement, particularly since the tables we fill are not particularly large so the loss in efficiency would be negligible here. Just to confirm is your proposed solution as simple as changing that single line in `tablefill.py`?

**Comment by lboxell** [comment]
Just changing that line worked for me in my situation.

**Comment by zkashner** [comment]
@lboxell circling back to this. Just implemented and pushed.
