### ISSUE TITLE
Discuss improvements to the template

### ISSUE THREAD

**Issue by Houdanait** [gentzkow/template#54]
The goal of this issue is to discuss improvements that can be made to the template going forward. Such improvements would in particular target smoother adaptations of repositories to specific needs of replication packages. 

Indeed, in creating the replication package for Phone Addiction, we face several issues and bugs as we were trying to adapt the environment to be run within Docker. 

Here are some take-aways from that process: 

> 
> 
> (1) We should make sure we're keeping Python/R dependencies to a minimum.
> 
> (2) We should disable functionality in the scripts that is interacting w/ Git (e.g., in defining ROOT and reporting repo characteristics for logging).
> 
> (3) We should test in the cloud environment or somewhere similar to make sure we're not relying on any idiosyncrasies of our own machines' setups.
> 
> (4) We should continue to explore using Docker.
> 

Here are some further comments by Lars : 

> 
> I think the fundamental issue that you have (as far as I can tell) already partially addressed is the idea of "exporting" your internal setup. While for instance using Git to check for ROOT is probably a MUST internally (to prevent accidentally not using Git), de-activating it, or having a fallback, might be useful for post-export.
> There are some subtleties about Docker that remain bothersome. While I managed to fix it, not sure that's the right approach (why would I need to use two separate YAML files with the exact same content as your single one? That points to some problem with Conda's solver, but it seems screwy.)
> 
> I would still encourage you to explore the following:
> 
> 1) Use the cloud resources, when possible, to assess robustness
> - for instance, using Github workflows
> 
> 2) Figuring out how those can harness confidential data as well
>  - Github workflows and codespaces allow for private keys - see my example with a Stata license - which can also be used to access Dropbox or Box APIs where the confidential data might be stored
> - those can be, in your environment, easily ported to a person-specific setup (the $HOME/.gslab/config file... 😉 ) but also by having simple branches (if Dropbox is local, use direct access, if not, use API)
> 
> I think the current Docker works, and can be reliably re-created. You might want to investigate how it differs from your project specific setup (I avoided the issue on how to activate an environment within Docker, since that would be two isolating environments when 1 is sufficient). I recreated it (and pushed it to Docker Hub) this morning, with the "one last run through" approach.

**Comment by szahedian** [comment]
Thank you @Houdanait for laying that out! Here's my take on the major points of discussion, ordered below from lightest to heaviest lift. 

> Disable functionality in the scripts that is interacting w/ Git (e.g., in defining ROOT and reporting repo characteristics for logging).

This sounds like a simple last step before exporting code for replication. We could just add as another step in the replication package README that the replicator should change `ROOT` as defined in [`run_all.py`](https://github.com/gentzkow/template/blob/d74838c1484b7e8aaeddea2bf88fd4ef7b91709f/run_all.py) to the absolute path to the root of the directory.

> Keep Python/R dependencies to a minimum.

We began examining this in #53. We determined that all `R` dependencies can be dropped from the base template. We are also in the process of dropping the `future` module, which we are pursuing in gslab-econ/gslab_make#49.

> Explore using Docker

For easy replication going forward, we may want a Docker image that produces an isolated environment for replication. Much of this work has already been done. Per his email of 14 April, Lars was able to build a container to replicate Digital Addiction. In #43, we demonstrated running the template inside a container.

Perhaps we could add to the template a `/Docker` directory, which would include a README and Dockerfile explaining how to build a replication container. For actual replication, we could build a replication container, push the container to Dockerhub, and delete the directory from the replication package. The replication instructions would then describe pulling the container from Dockerhub and running the replication package inside.

> Cloud environment e.g. Github Workflows

Lars recommends we test our code using cloud resources. If it's replicability we're after, I'm not sure if running in the cloud is any better than running a container on a local Docker daemon. But running on the cloud does have some advantages.

Lars specifically mentions [Github Workflows](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions). Workflows is not used for one-off testing, but for CI/CD — a common application is to check, on every push, that all code still runs. We could look into adding CI/CD pipelines to our projects. 

I think the potential benefits of CI/CD are two. First, catching broken code on small PRs that aren't reviewed. And second, catching mistakes that are specific to the code author's environment that the reviewer can't catch. 

Because Workflows run inside containers, implementing them would be much easier once we have a container setup we like.

**Comment by gentzkow** [comment]
@Houdanait @szahedian Picking up the discussion here again.

One question on @szahedian's last point: Do we know if it's possible to using Github Workflows to run proprietary (e.g., Stata, Matlab) software? Looks like this might require "hosting our own runner" per [here](https://docs.github.com/en/actions/hosting-your-own-runners)?

**Comment by szahedian** [comment]
@gentzkow apologies for the delayed response. After looking through the Github Actions about pages, my sense is that self-hosted runners are more flexible i.e. if we can't do it on a self-hosted runner, we can't do it on a Github runner. That said, I think it might be possible to possible to run Stata on a Github hosted runner, based on (1) the fact that Lars has figured out running Stata in Docker and (2) [this](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) guide to running Docker containers as Github actions. I'm less confident in our ability to run Matlab on a Github hosted runner. Please let us know what would be helpful next steps in this regard!

**Comment by gentzkow** [comment]
@Houdanait Thanks! The thing I find a bit baffling is how we've ended up in this situation

> There is an intense set up for the Gentzkow lab, we need to think of ways to make it simpler. In particular, the complex environment/set up, creates issues on Docker, which we want to avoid.

This setup typically involves just standard Python and R packages. I would have thought what we're doing is no more complex than a typical data science setup using these packages. Can we figure out where we went wrong in this respect?

**Comment by szahedian** [comment]
@gentzkow I've read the notes from Houda's call and reread our email chain with Lars. 

You said
> This setup typically involves just standard Python and R packages. I would have thought what we're doing is no more complex than a typical data science setup using these packages.

I think, given the dependencies we need for our projects, our setup is pretty streamlined. You thought similarly in an early email to Lars:

> We've designed this setup so it should be straightforward to run on any Linux / Mac environment and also easy on Windows provided the relevant applications are accessible from the command line. It should not require any alteration of the local environment other than making sure that Stata and Lyx are installed -- all the packages, etc. are installed within Conda.

To this, Lars responded

> I am comfortable on any environment, but my RAs use a university-managed Windows Server environment, and so the "easy on Windows" part doesn't work, because many of the pre-requisites are not satisfied

So it seems that, for many users on most environments, our setup can be replicated. But I think we can make setup even easier, so that users like Lars' RAs can replicate at all and those who already can replicate can replicate with greater ease. I think the way to do this, which is also mentioned in Houda's notes, is to build a replication Docker container for each replication package. 

Replication would then require two components.
1. A zip file with all project code
      1. We would make some changes before zipping, many of which I think we already do e.g. the GSLab [RA Manual](https://github.com/gslab-econ/ra-manual/wiki/Releases#replication-packages) lists some.
      2. We may want to make other changes, like setting ROOT manually (`run_all.py` still finds ROOT using git).
2. A pre-built Docker container with the environment necessary to run the code
     1. We already have some experience with this in #43.
     2. For Stata, the Dockerfile could borrow from Lars' [Stata in Docker](https://github.com/AEADataEditor/docker-stata)
     4. I think we could keep using `conda`. Thanks to Lars' hacking around, we now know some ways to make `conda` build environments much more quickly inside Docker.
     5. The built container would be made available on Docker Hub for replicators to pull down.

Replication would then, in theory, be as easy as (1) unzip the project code (2) run the Docker container, mounting the project code into the container (3) `python run_all.py`.

**Comment by gentzkow** [comment]
Thanks @szahedian 

I agree that a lot of arrows point toward Docker for replication!

What do you think are the best steps to take so we're ready to do that when we next come to produce a replication archive?

**Comment by gentzkow** [comment]
Sounds good! I'd vote you open a new task to move forward with it w/ a cap of no more than 10% of your time going to that task.

**Comment by gentzkow** [comment]
(And you can wrap up this task at the same time)

**Comment by Houdanait** [comment]
@gentzkow @szahedian Before we wrap this up!
One thing i wanted to raise is some discussion about `conda`. 
We moved the `template` to use `conda` a year ago. However, it seems that `conda` is not ideal if we want to use Docker and neither it is if we were to run the repository on Sherlock.
Do we want to do something about it? I.e., have include an option in the `template` to set up `conda` or to have the dependencies be encoded in another `txt` file (as was the case before)?

**Comment by szahedian** [comment]
Thanks, @Houdanait! 

I agree that conda was causing us issues on Docker. I think Lars found some workarounds that we may be able to use, but I agree that it's not ideal. If we move forward with Docker and conda continues to cause headaches, we could consider installing dependencies into Docker using other means e.g. pip. With Docker, we don't have to worry about affecting a user's base environment installations.

I was unaware that conda doesn't work well on Sherlock (I haven't used Sherlock much). Though it seems that pre-built container on Dockerhub can be used on Sherlock using [Singularity](https://www.sherlock.stanford.edu/docs/software/using/singularity/#importing-containers).

**Comment by szahedian** [comment]
@gentzkow I have one question before we close this issue. Lars suggested

> (2) We should disable functionality in the scripts that is interacting w/ Git (e.g., in defining ROOT and reporting repo characteristics for logging).

I think this makes sense for replication purposes. Should we make a note of this somewhere? In general, where would be a good place to post best practices / steps for turning a working project repo into a replication package?

**Comment by gentzkow** [comment]
Oh, good catch. Yes. 

Can you open a separate issue to implement? At a minimum, we can just add instructions for doing that to the section of the RA manual on replication archives ([here](https://github.com/gslab-econ/ra-manual/wiki/Releases)). We could also take a look to see whether there's any functionality we should add to the template or gslab_make to facilitate this. I think we already got rid of the github calls for defining ROOT. For the logging calls, we might want to set it up so it only delivers a warning but doesn't break in the event that git is not available.

**Comment by gentzkow** [comment]
Right. Only edit would be on (1) we should change the template so `run_all.py` never uses git to find ROOT. We should just assume `run_all.py` lives at ROOT.

**Comment by szahedian** [comment]
## Summary

In this issue, we discussed improvements to the template based on correspondence with Lars Villhuber. At this stage, we agreed to
1. Simplifying package dependencies as much as possible
2. Using Docker to build an isolated environment for replicators

Progress on (1) has been made on this issue's branch and in gslab-econ/gslab_make#51. Progress on (2) is being made in #56.
