### ISSUE TITLE
Issue with "Use this template" and Git LFS integration

### ISSUE THREAD

**Issue by snairdesai** [gentzkow/template#78]
The purpose of this issue (#78) is to address issues with the integrations of `git-lfs` raw files and the ability to use `~\gentzkow\template` directly in template format. I've run into issues using this repository as a template for other independent projects, because the `git-lfs` files hosted on the repo are not properly tracked to any new repo initialized with this `~/template` skeleton. Ngoc ran into the same issue when she was onboarding, as did BW when using `~/template` to initialize another project for the team.

We've determined that forking `~/template` to a new project allows for the transfer of `git-lfs` files, but ideally we would correct this integration element to enable the "Use as template" procedure. `GitHub` suggests this might not be easily solvable (see screenshot below), but it is worth some investigation to see if there are workarounds.

<details>

<img width="1080" alt="Screen Shot 2023-03-21 at 12 38 02 PM" src="https://user-images.githubusercontent.com/63830369/226722232-84c69aa5-29b6-438d-9a42-e5414a3d5c6e.png">

<summary>Screenshot from GitHub Docs</summary>
</details>

@jc-cisneros and I are assigned here.

**Comment by snairdesai** [comment]
_Updates:_ I haven't yet been able to find a perfect workaround here, but I've confirmed once more that forking the repository to a new version (rather than `Use as template`) works in the way that we need. We can also duplicate `template` using the `mirror` approach from `git`. More on this [here](https://docs.github.com/en/github-ae@latest/repositories/creating-and-managing-repositories/duplicating-a-repository#mirroring-a-repository-that-contains-git-large-file-storage-objects). I'll continue to look into this further in case another approach presents itself.

**Comment by snairdesai** [comment]
@gentzkow Thanks for flagging this issue! Yes, will look through the thread and keep you posted with updates here.

**Comment by snairdesai** [comment]
From first glance, seems like a potential issue might have arisen with [this commit](https://github.com/gentzkow/template/commit/da96c517b5e50a845b3a5f3a95966789369a431f) back to `master`. It seems all the `lfs-filter` lines were added back to `.gitattributes`. Need to look more closely, just flagging for myself.

**Comment by jc-cisneros** [comment]
@gentzkow @snairdesai let me share my current understanding of what is happening.

@snairdesai outlined these steps to test what would happen if we committed the changes in [f610f7e](https://github.com/gentzkow/template/commit/f610f7eb63edafa38e350607d48ed78e87e6e3b0) to master:

> 1. Fork template to another personal repo.
> 2. Clone down the forked repo, and commit + push the change to .gitattributes which is given in [f610f7e](https://github.com/gentzkow/template/commit/f610f7eb63edafa38e350607d48ed78e87e6e3b0) to its master branch (i.e., so that we don't directly commit to gentzkow/template/master for the moment).
> 3. Use the forked repository as a template with the green button at top. Make a new repository with a name of your choice (i.e., templatetester).
> 4. Pull down this newly created repository and try to access the git-lfs files 

Using `git lfs pull` on the fourth step resulted in the following error: 
> Failed to fetch some objects from 'https://github.com/jc-cisneros/template_test.git/info/lfs'

My sense is that if you create a new repository with the "Use as template" option GitHub moves the git-lfs pointer from the original owner of the template to the account that is creating the new repository (i.e., chips.csv and tv.csv are stored on @gentzkow's git-lfs account). GitHub documentation explicitly mentions that Git-LFS [cannot be used with templates](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage):
<img width="734" alt="Screenshot 2023-03-31 at 3 10 09 PM" src="https://user-images.githubusercontent.com/108437517/229241847-83c94b7c-5f2d-4638-9cd3-084aac8a73a5.png">

@jmshapir found the same issue on https://github.com/JMSLab/Template/issues/45. Given that it is still the case that there is no support for Git-LFS on template figures, we have the same options outlined by @jmshapir on that thread:
1)  Move all lfs-tracked files in the Template to git storage and remove lfs from the Template repo.
2) Add all lfs-tracked files in Template to the .gitignore and remove these files from the Template repo. (But retain the .gitattributes and therefore lfs itself.)
3) Turn off the option of using Template as a template repository, so that in order to use it, users have to clone it and then copy it over to their new repository.

They decided to go for (2), but for this repo I am more inclined towards (1). Given that chips.csv and tv.csv are only 8.8 MB and 99 KB respectively, it does not hurt to keep them in the normal Git storage. We could tweak the practice exercises and include storing these files in Git-LFS as part of the process.

**Comment by snairdesai** [comment]
@jc-cisneros I agree with the above, and the errors you receive match my own expectation. From [this comment](https://github.com/gentzkow/template/issues/78#issuecomment-1492229404) by @gentzkow, my sense is that in #51 the goal was to entirely rid the repository of `git-lfs`, and initialize this as part of our `setup` procedure (i.e., external to the `clone` process). I would have expected the reversion made in [`f610f7e`](https://github.com/gentzkow/template/commit/f610f7eb63edafa38e350607d48ed78e87e6e3b0) would address this concern in child repos, but it does not seem that making this change fixes the issue for either of us.

Let me read through the thread in https://github.com/JMSLab/Template/issues/45 more closely and get back to you.

**Comment by snairdesai** [comment]
I'm also wondering if something happened to the `raw` files themselves between the commits made in #51 and those since then which is resulting in an issue. I'll generate a `diff` shortly.

**Comment by gentzkow** [comment]
Thanks guys. I am fine setting things up so there are no lfs-tracked files in the template repo. We'll just want to make sure that the setup process requires people to turn on lfs unless they explicitly opt not to.

**Comment by snairdesai** [comment]
Sounds good @gentzkow! Will implement shortly and update the `README`.

**Comment by snairdesai** [comment]
_For myself:_ Complete list of `lfs` files currently living in `template` repo:

<img width="294" alt="Screen Shot 2023-04-01 at 11 05 05 AM" src="https://user-images.githubusercontent.com/63830369/229307264-d691ea39-ff41-44ff-a0c8-ccbb3853a740.png">

**Comment by snairdesai** [comment]
In commit [`0d7e60c`](https://github.com/gentzkow/template/commit/0d7e60c6e7d1f46fb853237075e127680058aadf), I renormalized all of our tracked `lfs` files to standard `git`. The final steps here for me are:

- [ ] Update the `README`, and revise the `setup` procedure (if needed) to require `lfs` unless a user opts out.
- [ ] Check that the `lfs` tracking still works as expected when `template` is pulled down in its raw form with standard `git` tracking enabled.

**Comment by snairdesai** [comment]
In [`779d26e`](https://github.com/gentzkow/template/commit/779d26ecf1356da9b64008e80fa60c172f517fa9), I confirmed that running our current `~/setup` procedure (running `lfs_setup.sh`) correctly tracks and populates our files with `lfs`. I'll revert back to [`0d7e60c`](https://github.com/gentzkow/template/commit/0d7e60c6e7d1f46fb853237075e127680058aadf).

**Comment by snairdesai** [comment]
### Summary  + Deliverables
---

The purpose of issue (#78) is outlined in [this comment](https://github.com/gentzkow/template/issues/78#issue-1634575633). Users have had difficulties with the "use as template" option for generating child repos from `template`, due to an issue transferring ownership of `git-lfs` files across repositories. To address this, we decided to renormalize the raw files living in `template` to be stored with raw `git` rather than `git-lfs` and reverted to `.gitattributes` file to a prior version which was accidentally overwritten in a prior PR.

This issue followed in the associated PR (#79).
